# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: docker

# Trigger the workflow when:
on:
  # A push occurs to one of the matched branches.
  push:
    branches:
      - main

jobs:

  build-benchmarking-image:
    # NOTE: This name appears in GitHub's Checks API.
    name: build-benchmarking-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Check out pull request's HEAD commit instead of the merge commit.
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Determine tag name
        id: determine_tag
        uses: ./.github/actions/determine-tag

      - name: Determine oasis-core artifacts paths
        id: determine-artifacts-paths
        shell: bash
        run: |
          . tests/consts.sh
          . tests/paths.sh
          echo "::set-output name=oasis_core_node_binary_path::$(echo ${TEST_NODE_BINARY})"
          echo "::set-output name=oasis_core_runtime_loader_path::$(echo ${TEST_RUNTIME_LOADER})"
        env:
          TESTS_DIR: tests

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
      - name: Set up Go 1.17
        uses: actions/setup-go@v2.1.5
        with:
          go-version: "1.17.x"
      - name: Install Oasis dependencies
        run: |
          sudo apt-get update
          sudo apt-get install bubblewrap build-essential libseccomp-dev libssl-dev protobuf-compiler
      - name: Build benchmarks
        working-directory: tests/benchmark
        run: ./build-benchmarks.sh

      # Build and push benchmarks docker image.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: "Rebuild oasisprotocol/oasis-sdk-benchmark:${{ steps.determine_tag.outputs.tag }}"
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: tests/benchmark/Dockerfile
          tags: oasisprotocol/oasis-sdk-benchmark:${{ steps.determine_tag.outputs.tag }}
          pull: true
          push: true
          build-args: |
            OASIS_CORE_NODE_BINARY=${{ steps.determine-artifacts-paths.outputs.oasis_core_node_binary_path }}
            OASIS_CORE_RUNTIME_LOADER=${{ steps.determine-artifacts-paths.outputs.oasis_core_runtime_loader_path }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.determine_tag.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
